# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc5064116ab844d962b149ea32cdb2dc4a74b6ee480dff1f7462885b658082e941cffe7ab6d78c7e12901467b20fe46e5b0aa3722088ffb0e6b41bafbde7cd3e

test:
  secret_key_base: 40af13f80314cd7cbd495d6f137d1944fe098cfa2a35acb0d8a986e90cb92b6c6cfb86ca74ba5843b33266df6fa2e106fa3ef9289e2b916d12e73dc6cb41b382

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
